# Generated by Django 5.2 on 2025-04-28 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='book_category',
        ),
    ]
