# Generated by Django 5.2 on 2025-04-29 16:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0002_remove_library_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
