# Generated by Django 5.2 on 2025-04-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowingrecord',
            name='due_date',
            field=models.DateField(),
        ),
    ]
