# Generated by Django 5.2 on 2025-04-30 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
