# Generated by Django 5.2 on 2025-04-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0002_remove_author_bio_remove_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available_copies',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
